Repository cert-manager/csi-lib, pull requests merged in 2022-09, with the labels that each got.

#31 Change CertificateRequest owner reference of pod `core/v1` -> `v1`
  manager/manager.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#32 Use a passed through context to manager issue function
  manager/manager.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#35 Simplify issuance backoff handling & improve error messages
  deploy/cert-manager-csi-driver.yaml
  deploy/example/example-app.yaml
  driver/nodeserver.go
  manager/manager.go
  test/integration/ready_to_request_test.go
  test/util/testutil.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#36 Default renewal time to halfway through certificates lifetime
  manager/manager.go
  test/integration/issuance_test.go
  test/integration/ready_to_request_test.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#37 Add more exhaustive unit testing for manager
  manager/manager.go
  manager/manager_test.go
  manager/utils_test.go
  test/driver/driver_testing.go
  test/integration/issuance_test.go
  test/integration/ready_to_request_test.go
  test/util/testutil.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#39 manager: remove dependency on cert-manager's controller/test package
  go.mod
  go.sum
  manager/manager_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L
